
-- Tabela para armazenar os pedidos de orçamento (Formulário principal)
create table public.orcamentos (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  client_name text not null,
  phone text not null,
  service_type text,
  description text
);

-- Tabela para armazenar os leads (Pop-up "Aguardar Contato")
create table public.leads (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  whatsapp text not null
);

-- Habilitar segurança a nível de linha (RLS)
alter table public.orcamentos enable row level security;
alter table public.leads enable row level security;

-- Criar políticas para permitir que qualquer pessoa (anon) insira dados
-- Isso é necessário porque o site é público e usa a chave anon
create policy "Permitir inserção pública em orcamentos" 
on public.orcamentos 
for insert 
to anon 
with check (true);

create policy "Permitir inserção pública em leads" 
on public.leads 
for insert 
to anon 
with check (true);

-- Opcional: Políticas para leitura (SELECT) não são criadas para 'anon',
-- garantindo que usuários públicos não possam ler os dados de outros clientes.
